module Tokens = MParser_RE.Tokens

type symbol = { str : string; sep : string }

val make_symb : string -> symbol
val mk_keyw : string -> symbol
val symb_nullstr : symbol
val symb_false : symbol
val symb_true : symbol
val symb_or : symbol
val symb_and : symbol
val symb_ampersand : symbol
val symb_emp : symbol
val symb_star : symbol
val symb_pointsto : symbol
val symb_array : symbol
val symb_eq : symbol
val symb_deq : symbol
val symb_lt : symbol
val symb_leq : symbol
val symb_plus : symbol
val symb_times : symbol
val symb_lp : symbol
val symb_rp : symbol
val symb_ls : symbol
val symb_rs : symbol
val symb_lb : symbol
val symb_rb : symbol
val symb_semicolon : symbol
val symb_colon : symbol
val symb_comma : symbol
val symb_turnstile : symbol
val symb_turnstile_underscore : symbol
val symb_ind_implies : symbol
val symb_ind_sep : symbol
val symb_assign : symbol
val symb_bang : symbol
val symb_caret : symbol
val symb_mapsto : symbol
val symb_final : symbol
val symb_box : symbol
val symb_diamond : symbol
val symb_circle : symbol
val symb_next : symbol
val symb_f : symbol
val symb_g : symbol
val symb_fld_sel : symbol
val symb_dot : symbol
val keyw_exists : symbol
val keyw_final : symbol
val keyw_true : symbol
val keyw_emp : symbol
val keyw_free : symbol
val keyw_new : symbol
val keyw_goto : symbol
val keyw_if : symbol
val keyw_fi : symbol
val keyw_then : symbol
val keyw_else : symbol
val keyw_stop : symbol
val keyw_return : symbol
val keyw_nil : symbol
val keyw_fields : symbol
val keyw_judgement : symbol
val keyw_precondition : symbol
val keyw_postcondition : symbol
val keyw_property : symbol
val keyw_proc : symbol
val keyw_skip : symbol
val keyw_while : symbol
val keyw_do : symbol
val keyw_od : symbol
val keyw_assert : symbol
val parse_symb : symbol -> 'a MParser.state -> (unit, 'a) MParser.reply
