# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cyclist
email: nikos.gorogiannis+www@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cyclist is a framework for building cyclic theorem provers.
  Several such provers are included 
  focusing on Separation Logic with inductively defined predicates.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cyclist-prover.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
