tree_add_left tree(node)
tree_add_left node != nil * l' = nil * node->l',r',p',n' * context(node,p') * subtree(l',node) * subtree(r',node)
tree_add_right tree(node)
tree_add_right node != nil * r' = nil * node->l',r',p',n' * context(node,p') * subtree(l',node) * subtree(r',node)
tree_dispose tree(node)
