llist_add llist(list)
llist_append llist(list1) * llist(list2)
llist_dispose llist(list)
llist_length llist(list)
line_206- lseg2(f,n,l) * lseg(n,l)
llist_lookup llist(list)
line_239- lseg(f,n) * lseg(n,l)
llist_removeFirst llist(l)
llist_create_iter llist(l)
iter_next i != nil * list' != nil * l' != n' * i->n' * list'->f',l' * l'->m',w' n'->nxt',v' * lseg2(f',n',l') * lseg(nxt',l')
iter_dispose iter(i,l') * llist(l')
