queue_try_dequeue queue != nil * queue->n',f',m',l' * lseg2(f',m') * lseg(l',m')
line_604- middle->v',w' * lseg(prev, middle) * lseg2(node, last)
queue_dispose queue != nil * queue->n',f',m',l' * lseg2(f',m') * lseg(l',m')
line_659- lseg2(first, middle)
line_667- lseg2(first,middle) * lseg(last,middle)
