(** A proofrule used by a cyclic prover. *)

open Lib

module type S = sig

  type seq_t

  type infrule_t

  type proof_t

  type axiom_f = seq_t -> infrule_t option

  type infrule_f =
    seq_t -> ((seq_t * Tagpairs.t * Tagpairs.t) list * infrule_t) list

  type backrule_f = seq_t -> seq_t -> Tagpairs.t list

  type select_f = int -> proof_t -> int list

  (** The type of proof rules:
      Proof rules are functions that take an open node in a proof (i.e. an int
      identifying the node, and the proof structure containing the node) and
      return a list of new proofs that are obtained by applying the rule in all
      applicable ways to the open node in the provided proof, along with a list
      for each new proof of the newly added open nodes (i.e. the premises)
  **)
  type t = int -> proof_t -> (int list * proof_t) list

  val mk_axiom : axiom_f -> t
  (** Axioms are modeled as functions that return [Some rule] when the
      input sequent is an instance of an axiom described by the value [rule],
      else [None] if the input sequent is not an instance of the axiom. *)

  val mk_infrule : infrule_f -> t
  (** Rules are functions that break down a sequent to a choice of applications
      where each application is a list of premises, including tag information,
      and a description. *)

  val mk_backrule : bool -> select_f -> backrule_f -> t
  (** Backlink rules take:
        - a boolean [eager]
        - a selection function [s]
        - a matching function [m]

      The selection function is applied on the current subgoal and proof, and
      a list of goal indices is returned that represents possible back-link
      targets. This allows flexibility e.g., in changing from ancestral-only
      back-links to general ones.

      Next, [m] is applied to every pair consisting of the current subgoal
      and a goal returned from the selection function. [m] returns a list of
      tag information and string descriptions, each describing a different
      way to form a back-link.

      If [eager] is true then the first result in this iteration will be chosen
      and no back-tracking will even happen over later possible matches.
      Otherwise all possible matches are returned as different choices.
      *)

  val all_nodes : select_f
  (** Ready-made selection function doing the obvious. *)

  val closed_nodes : select_f
  (** Ready-made selection function doing the obvious. *)

  val ancestor_nodes : select_f
  (** Ready-made selection function doing the obvious. *)

  val default_select_f : select_f ref
  (** A reference to a default selection function (one of the above). *)

  val set_default_select_f : int -> unit
  (** Specify the selection function to store as the default *)

  val default_select_f_descr : ?line_prefix:string -> unit -> string
  (** Returns a description of the inputs for the [set_default_select_f] function. *)

  val fail : t
  (** The rule that always fails. *)

  val identity : t
  (** Return current subgoal and proof as application. *)

  val attempt : t -> t
  (** Try a rule and if it fails act as [identity]. *)

  val non_empty : t -> t
  (** [non_empty r] fails if the rule [r] acts as the identity, else it acts as
      the application of [r]. *)

  val compose : t -> t -> t
  (** Apply the second rule on all premises generated by applying the first. *)

  val compose_pairwise : t -> t list -> t
  (** Apply the list of rules in the second argument in a pairwise fashion to
      the premises generated by applying the first rule.
      If there are more rules than subgoals, then discard remaining rules.
      If there are fewer rules than subgoals, apply [identity] to the remaining
      subgoals. *)

  val choice : t list -> t
  (** Apply a list of rules on current subgoal and return all applications. *)

  val first : t list -> t
  (** Try rules from a list until the first rule is found that has some
      applications on current sugboal and return only those. *)

  val sequence : t list -> t
  (** Apply a sequence of rules iteratively through [compose]. *)

  val conditional : (seq_t -> bool) -> t -> t
  (** [conditional p r] applies the rule [r] to a given open node with sequent
      [seq] if [p seq] returns [true], and fails otherwise. *)

  val unless : (seq_t -> bool) -> t -> t
  (** [unless p r] applies the rule [r] to a given open node with sequent [seq]
      unless [p seq] returns [true], in which case it fails.
      This is equivalent to [conditional (fun s -> not (p s)) r].
      This inference rule combinator is provided for readability. *)

  val repeat' :
    ?while_:(int -> proof_t -> bool) -> ?until:(int -> proof_t -> bool)
        -> ?failure_as_termination:bool -> ?eager:bool -> t -> t
  (** [repeat' ~while_ ~until ~terminate_on_failure ~eager r] keeps applying the
      rule [r] recursively (i.e. on subgoals newly generated by previous
      applications) as long as possible (i.e. as long as it succeeds) or
      until subgoals satisfy the predicate [until], at which point it stops.
      If the (sub)goal to which the (recursive) rule application is made fails
      to satisfy the predicate [while_] then so does the (recursive) rule
      application.
      If the flag [failure_as_termination] is [false], then (recursive)
      applications of the rule also fail when the rule [r] fails.
      If the flag [eager] is [true] then (recursive) applications of the rule
      will return the first closed (sub)proof that is found (i.e. if the
      repeated application of [r] results in multiple closed (sub)proofs, only
      the first one that is found will be returned). If there are no closed
      (sub)proofs, then all (open) (sub)proofs obtained by recursively applying
      [r] are returned.
      The default values of [while_], [until] and [failure_as_termination] are
      the constant [true] function, the constant [false] function, and the
      boolean value [true], respectively. *)

  val repeat : t -> t
  (** [repeat r] keeps applying rule [r] recursively as long as possible.
      If the application of [r] fails immediately, then act as identity.
      This is functionally equivalent to applying [repeat'] with the default
      values of the named arguments [while_], [until] and
      [failure_as_termination], but avoids the explicit checks associated with
      them (thus is marginally more efficient).
      Care should be taken when using this combinator, as applying [repeat r]
      will only terminate in case the rule [r] represents a terminating proof
      search strategy. *)

end

module Make (Seq : Sequent.S) (Infrule : Infrule.S)
    : S with type seq_t := Seq.t
         and type infrule_t := Infrule.t
         and type proof_t := Proof.Make(Seq)(Infrule).t
